run:
  timeout: 5m

linters:
  enable:
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosec
    - gofmt
    - goimports

linters-settings:
  gosec:
    excludes: []

issues:
  exclude-use-default: false
